# Generated by Django 4.1.6 on 2023-03-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user',
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
