# Generated by Django 4.1.6 on 2023-03-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_remove_seller_user_delete_buyer_delete_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('seller', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
