# Generated by Django 4.1.6 on 2023-03-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='cart.png', upload_to='pics'),
        ),
    ]
