# Generated by Django 4.1.7 on 2023-03-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('food', 'FOOD'), ('snacks', 'SNACKS'), ('clothes', 'CLOTHES'), ('shoes', 'SHOES'), ('accessories', 'ACCESSORIES'), ('miscellaneous', 'MISCELLANEOUS')], default='miscellaneous', max_length=20),
        ),
    ]
