# Generated by Django 4.1.7 on 2023-03-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_details_product_rating_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='picture1',
        ),
        migrations.AddField(
            model_name='product',
            name='picture2',
            field=models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture3',
            field=models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture4',
            field=models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='picture5',
            field=models.ImageField(blank=True, default='cart.png', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_email',
            field=models.EmailField(default='example@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_telegram_number',
            field=models.CharField(default='123456789', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_whatsapp_number',
            field=models.CharField(default='123456789', max_length=12),
            preserve_default=False,
        ),
    ]
