# Generated by Django 4.1.7 on 2023-03-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_picture_product_picture1_product_picture2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
