# Generated by Django 4.1.7 on 2023-03-18 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('food', 'FOOD'), ('snacks', 'SNACKS'), ('clothes', 'CLOTHES'), ('shoes', 'SHOES'), ('accessories', 'ACCESSORIES'), ('gadgets', 'GADGETS'), ('miscellaneous', 'MISCELLANEOUS')], default='miscellaneous', max_length=20),
        ),
    ]
