# Generated by Django 4.1.7 on 2023-03-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(default='No details on this product'),
        ),
    ]
