# Generated by Django 4.1.7 on 2023-03-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_number_rating_remove_product_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('feedback', models.TextField(default='No feedback')),
                ('product', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
