# Generated by Django 4.1.7 on 2023-03-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cart_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='arating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
        ),
    ]
