# Generated by Django 4.1.7 on 2023-03-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feedback_rating_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='arating',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
