# Generated by Django 4.1.7 on 2023-03-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_feedback_rating_product_arating'),
        ('core', '0017_product_arating_alter_product_rating'),
    ]

    operations = [
    ]
