# Generated by Django 4.1.7 on 2023-03-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20230331_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_instagram_number',
            field=models.CharField(default='@instagram', max_length=12),
        ),
    ]
